name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
      - name: Run the build script
        run: |
          bash ./jupyter2md.sh
          pipenv run python process.py
      - name: Push to GitHub Pages
        run: pipenv run ghp-import -n -p -f docs
